import type { Metadata } from "next";
import { Public_Sans  } from "next/font/google";
import "./globals.css";
import { DarkModeProvider } from "@/context/DarkModeContext";

const roboto = Public_Sans({
	variable: "--font-roboto",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${roboto.className} antialiased`}
			>
				<DarkModeProvider>
					{children}
				</DarkModeProvider>
			</body>
		</html>
	);
}